### ISSUE TITLE
Not friendly to vue3. The animation cannot be displayed when I load the page for the first time. How should I solve it?

### ISSUE THREAD

**Issue by Cherryboyy** [ingram-projects/animxyz#107]

**Comment by mattaningram** [comment]
Can you provide a few more details? It should work fine with Vue 3. When you say "load the page for the first time" do you mean the animation runs when you reload the page after the first time?

**Comment by Cherryboyy** [comment]
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/50610945/187330672-926e1908-acea-4b90-9a01-0062b9f281ca.png">
first hide the element and display the element through the click event. There is no dynamic effect when it is displayed for the first time. It only works when I repeat it many times. You can try to realize the content of my picture, thank you

**Comment by ricky11** [comment]
dont you need a key on each div.
