### ISSUE TITLE
the animations in the documentation right side are distracting

### ISSUE THREAD

**Issue by boussadjra** [ingram-projects/animxyz#12]
Thanks for this awesome library, but there's something that annoys me which is the animations that play in the right side of documentation that could distract the reader, I suggest to add a play button, thanks again.

**Comment by sjclark** [comment]
I completely disagree - the animations are only shown when they are directly relevant to the content, they're very minimal and unobtrusive. Also this is quite literally an animation library - animations are the entire purpose.

If you're not a fan of animations in general then you can toggle your OS's (or browsers) reduced motion toggles.

**Comment by boussadjra** [comment]
@sjclark thanks for your reply, I respect your opinion, but I didn't say that they should deactivate it but just add `run animation` button that allow the user to play the animation when he wants.

**Comment by mattaningram** [comment]
On the one hand @sjclark is right that animations are the whole point, on the other hand even I get annoyed by some of the animations when trying to work on and edit the docs.

Maybe a good half-way solution is to keep the animations running by default, but to have a "Pause Animations" button you can click if they are getting on your nerves. Shouldn't be too hard to implement.

**Comment by boussadjra** [comment]
@mattaningram thanks, that's the solution that I'm looking for.
