### ISSUE TITLE
nested + staggered start the animation of the second parent only when the first has finish ?

### ISSUE THREAD

**Issue by flapili** [ingram-projects/animxyz#16]
Hi, I would like to know if there is a possibilty to start the animation of a second parent only when the animation of the parent and their child as finished.

My case is animate each letter of a title but I can't just loop over the title because of the wrap:
![image](https://user-images.githubusercontent.com/29481952/103159360-cb9c9500-47c8-11eb-9ef9-20a635133ccd.png)
in the screen the world "itérateurs" should be wrapped in the next line.

my current code is:
```html
                <XyzTransitionGroup
                  appear
                  xyz="fade small up stagger duration-30"
                >
                  <div
                    v-for="(word, i) in article.title.split(' ')"
                    :key="`title-${i}`"
                    style="display: inline"
                  >
                    <template v-if="i != 0">&nbsp;</template
                    ><span
                      v-for="(char, i2) in word"
                      :key="`title-${i}-${i2}`"
                      class="xyz-nested"
                      :ref="`title-${i}-${i2}`"
                      >{{ char }}</span
                    >
                  </div>
                </XyzTransitionGroup>
```

**Comment by milesingrams** [comment]
Hi Flapili! There are two ways to fix this which I have put in the linked CodeSandbox.

Approach 1: Use an XyzTransition component and give each span an xyz-nested class and add an --xyz-index (This is because the default CSS only sets the index for the first 20 elements).

Approach 2: Use an XyzTransitionGroup component wrapping the spans.

https://codesandbox.io/s/animxyz-letters-stagger-example-1rq8b?file=/src/App.vue

**Comment by milesingrams** [comment]
Let me know if this solves your issue or if you have any additional questions! Thanks for using our library and for helping us improve it.

**Comment by flapili** [comment]
Hi, unfortunately that doesn't solve the main issue which is the new line in a word
![image](https://user-images.githubusercontent.com/29481952/103283224-412a8000-49d8-11eb-8193-e61daaa73452.png)

that why I must have 2 loops: one for the word and a second, nested, for the char in the word.
```html

```

**Comment by milesingrams** [comment]
You should be able to do this using a computed property?  https://vuejs.org/v2/guide/computed.html
Basically you can map the title to a nested array where each char is associated with a global index.

Check out the last example in the codesandbox I updated: https://codesandbox.io/s/animxyz-letters-stagger-example-1rq8b?file=/src/App.vue

**Comment by milesingrams** [comment]
Note that for appear animations only you can do it without an XyzTransition or XyzTransitionGroup component if you want. Those are mostly helpful if the content is dynamic and you want in and out animations as elements are added and removed.
