### ISSUE TITLE
React Support

### ISSUE THREAD

**Issue by beamercola** [ingram-projects/animxyz#17]
I see it's coming soon but not sure where to follow for updates

**Comment by mattaningram** [comment]
It's high on our priority list, and we are looking into the best way to approach it. The current WIP version we have published may change significantly (thus why no docs yet).

I am looking into creating a Github project board or Trello to better communicate roadmap and whats in progress.

**Comment by mattaningram** [comment]
@beamercola Ok added a project board here to provide at least some high level idea of what we are working on: https://github.com/ingram-projects/animxyz/projects/1

**Comment by Florian-crg** [comment]
When will you support React ? It's confusing that on your website you seemed to support React...

**Comment by MichaelKheel** [comment]
> When will you support React ? It's confusing that on your website you seemed to support React...

I agree, I wanted to try the library, but I was faced with the fact that I could not import it :)

**Comment by mattaningram** [comment]
Hey folks, we know it's been a long time coming, but thanks to @milesingrams hard work we're excited to release full React support with v0.6.0. You can find the docs for installing and using the [React integration here](https://animxyz.com/docs#react-installation).

We'd love to hear any feedback you have and submit an issue if you find any bugs!

**Comment by Florian-crg** [comment]
@mattaningram Since animxyz is a composable CSS animation toolkit is it compatible react-native ?

**Comment by mattaningram** [comment]
@Florian-crg Unfortunately react-native doesn't support CSS animations so it isn't compatible there.
