### ISSUE TITLE
Animate on scroll

### ISSUE THREAD

**Issue by Sananes** [ingram-projects/animxyz#21]
Would be great to automatically trigger  animation on scroll through some extra config / props. This would be a great enhancement if I say so myself.

**Comment by mattaningram** [comment]
Definitely something we are looking at! In the meantime you can use other 3rd party scroll libraries to add the `xyz-in` or `xyz-out` classes as you scroll.

**Comment by EdwardEvad3rs** [comment]
Waiting for this too! If it comes with scroll trigger features, that will be great, this is a good animation library, will use this in next project!

**Comment by Sananes** [comment]
@mattaningram do you happen to know of any 3rd party scroll library that you could recommend that would work nicely with this?

**Comment by florian-lefebvre** [comment]
There is [vue-observe-visibility](https://github.com/Akryum/vue-observe-visibility).

**Comment by brianfryer** [comment]
@Sananes waypoints.js is great out-of-the-box solution.

You can always use the Intersection Observer API, too ([link](https://medium.com/@mciastek/animate-on-scroll-with-intersection-observer-ea744cddb876)).

**Comment by mattaningram** [comment]
WIP PR for triggering animations on scroll is here: https://github.com/ingram-projects/animxyz/pull/30 and you can keep track of this and other work in our project board: https://github.com/ingram-projects/animxyz/projects/1

**Comment by imprakharshukla** [comment]
Great! I was looking for on-scroll support and it's already completed. Thank you for this amazing lib. **Any idea when it's actually pushed to npm?** 

I would also recommend versioning the docs so that the features not yet available aren't documented.

**Comment by milesingrams** [comment]
Good idea! I need to figure out how to set up versioning for docs so there isn't a gap between what shows up on the site and when the packages are released. I'll be publishing the packages today, just have to do a final check! I'll comment here when done :)

**Comment by milesingrams** [comment]
@imprakharshukla Deployed and ready to go!
Version 0.4.0.
Give it a shot and let us know how it works!

**Comment by Sananes** [comment]
Thank you! You guys are awesome! Great job!
