### ISSUE TITLE
Maintain the height of an element when it is out with Vue

### ISSUE THREAD

**Issue by florian-lefebvre** [ingram-projects/animxyz#29]
Hello, I use AnimXYZ in my Vue project. I made a component to trigger the animation when scrolling using the Intersection Observer API but my problem is that AnimXYZ reduces the element where I have `v-if="show"` when it's false. Is it possible to keep the height of the original element and the animation ?

**Comment by mattaningram** [comment]
You can have the intersection observer apply the `xyz-in` or `xyz-appear` class to the elements you want to animate instead of using `v-if` or `v-show` logic. Let me know if that works.

**Comment by florian-lefebvre** [comment]
Yes, I just replaced `v-if="show"` by `:class="show ? 'xyz-appear' : null"` and it worked. Thanks!

**Comment by florian-lefebvre** [comment]
This is now useless, use `appear-visible` attribute. See https://animxyz.com/docs#vue-xyz-transition.

**Comment by florian-lefebvre** [comment]
@ricky11 I think you should look at `appear-visible` properties: https://animxyz.com/docs#vue-xyz-transition, and in particular the `IntersectionObserverOptions`.
