### ISSUE TITLE
No declaration file for Module @animxyz/vue3

### ISSUE THREAD

**Issue by DiemoHeuer** [ingram-projects/animxyz#31]
Hey,
I followed you instructions on your [Docs](https://animxyz.com/docs/#vue-installation) for setting up AnimXYZ with Vue 3 (and Tailwind 2) and was running into the following error: 

```
ERROR in src/main.ts:6:24
TS7016: Could not find a declaration file for module '@animxyz/vue3'. 'C:/Development/projects/musicxml-analyzer-app/node_modules/@animxyz/vue3/dist/VueAnimXyz.cjs.js' implicitly has an 'any' type.
  Try npm install @types/animxyz__vue3 if it exists or add a new declaration (.d.ts) file containing declare module '@animxyz/vue3';
    4 | import store from "./store";
    5 | import "./tailwind.css";
  > 6 | import VueAnimXYZ from '@animxyz/vue3'
      |                        ^^^^^^^^^^^^^^^
    7 | import '@animxyz/core' ;
    8 | 
    9 | createApp(App)
```

May it be that the Vue 3 support is not complete at the moment or did I forget somethin in the setup?
If you need further information, just let me know.

Some help would be appreciated!

**Comment by milesingrams** [comment]
Ah, I may need to migrate the plugins to typescript or write an index.d.ts declaration file. In the meantime you can either write a simple declaration file to remove the warning or turn off noImplicitAny in your tsconfig. Hopefully I can get to this soon.

**Comment by DiemoHeuer** [comment]
Hey,
thank you for the link. I read it and some of the referenced links in the article. But unfortunately I'm stuck again because I can't figure out how to use noImplicitAny or to create a simple declaration file to get rid of my problem. I'm just getting started with Vue and TypeScript and some basic knowledge is still missing. I will try to figure it out myself.

But... if you have the time to help me futher with a wuick workaround to get AnimXyz running with Vue 3, I would be very happy ;)

**Comment by bitterlox** [comment]
@DiemoHeuer If your vue 3 project has a `shims-vue.d.ts` file in src directory ( if you initialized the project with vue-cli it should be present) add this line to turn off type checking for the library:
```
declare module "@animxyz/vue3";
```
I've been using a couple of other libraries without type definitions and this trick saved me a lot of headaches.

**Comment by DiemoHeuer** [comment]
@bitterlox thank you for the help! The error message depending the types is gone and I now can build the project.

Now I have tried the basic example from the documentation in one of my components:

```
    <div>
      <XyzTransition xyz="fade up big">
        <div class="square"></div>
      </XyzTransition>
    </div>
```

That resulted in following error messages:

```
[Vue warn]: Unhandled error during execution of render function 
  at <BaseTransition onEnter=fn onLeave=fn<onLeave> appear=false  ... > 
  at <Transition css=true type="animation" appearFromClass="xyz-appear-from"  ... > 
  at <XyzTransition xyz="fade up big" > 
  at <App>

```
and

```
Uncaught TypeError: Cannot read property 'length' of null
    at filterSingleRoot (runtime-core.esm-bundler.js?5c40:855)
    at getChildRoot (runtime-core.esm-bundler.js?5c40:834)
    at renderComponentRoot (runtime-core.esm-bundler.js?5c40:743)
    at componentEffect (runtime-core.esm-bundler.js?5c40:4193)
    at reactiveEffect (reactivity.esm-bundler.js?a1e9:42)
    at effect (reactivity.esm-bundler.js?a1e9:17)
    at setupRenderEffect (runtime-core.esm-bundler.js?5c40:4176)
    at mountComponent (runtime-core.esm-bundler.js?5c40:4134)
    at processComponent (runtime-core.esm-bundler.js?5c40:4094)
    at patch (runtime-core.esm-bundler.js?5c40:3712)
```

The second warning disappears when I try to import the Component (but I'm not shure if this is the right way):

```
import XyzTransition from "@animxyz/vue3";
export default defineComponent({
  components: {
    XyzTransition,
  },
...
})
```

Is there something else that I have to be aware of?

**Comment by milesingrams** [comment]
Added basic declaration file for all plugins which should remove the error. Sorry it took a while! Will add more comprehensive types once we do a full switchover to typescript.
