### ISSUE TITLE
Is there a way to trigger these animations on scroll?

### ISSUE THREAD

**Issue by Ayman97** [ingram-projects/animxyz#33]

**Comment by mattaningram** [comment]
Yes! If you're using our Vue plugin you can use `appear-visible` attribute documented here: https://animxyz.com/docs#vue-xyz-transition

If you are using your own scroll trigger setup then you can apply the `xyz-in` and `xyz-out` classes using that.

Let me know if you have any questions! We use it on our docs and landing page if you want to see it in action.

**Comment by Ayman97** [comment]
Just in the right time, i used another animation library yesterday but i will definitely use yours. Thanks!

**Comment by mattaningram** [comment]
Great to hear! Let us know if you have any issues with `appear-visible` or anything else in the library.

**Comment by ricky11** [comment]
Would it be possible to trigger the xyz-out animation when the div is almost out of view? I believe vue has the appear tag which is what you are using for xyz-in, but how would i animate on when the intersection observer div is almost out of the page?
