### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by tomer953** [ingram-projects/animxyz#36]
Hi,

any intentions to creating adapter for Angular 8+ ?

Thank you.

**Comment by milesingrams** [comment]
Hi Tomer,
Right now we are prioritizing making an adapter for React but after that is done we will investigate whether it would be possible to make an Angular adapter. The main challenge with angular is that is has a very opinionated transition module that doesn't allow adding and removing classes which would make building an adapter for it quite difficult. But perhaps there is a way!

**Comment by tomer953** [comment]
Ok.
looking forward to that support.
