### ISSUE TITLE
Should elements be block elements?

### ISSUE THREAD

**Issue by dannykoshy** [ingram-projects/animxyz#44]
Hi,

I was trying out the react package for the AnimXYZ. Its really fun to play around. But I have a small query.

Does the element which we want to animate be block elements? Because when i animate a span element the animation doesnt work.

Looking forward from you!

**Comment by mattaningram** [comment]
Hi Danny,

CSS animations don't work on purely `inline` elements, so I would suggest adding `display: inline-block;` to the `<span>` you want to animate.

Let me know if that works!

**Comment by dannykoshy** [comment]
> Hi Danny,
> 
> CSS animations don't work on purely `inline` elements, so I would suggest adding `display: inline-block;` to the `<span>` you want to animate.
> 
> Let me know if that works!

Hi Matt,

This solution I already had. But there will be situations where I want to keep the display property something other than block or inline-block.

Or maybe I am using a 3rd party component which I might not have control on.

Anyways thanks for the reply!

**Comment by mattaningram** [comment]
@dannykoshy It will work with anything except pure `inline` elements, so `flex`, `inline-flex`, `grid`, etc will all be fine.
