### ISSUE TITLE
Modals problem

### ISSUE THREAD

**Issue by veliborr** [ingram-projects/animxyz#47]
Hello, everytime there is modal in an component looks like xyz overrides it's z-index. When I comment out XyzTransition everything goes back to normal. Do you know what could be a problem? Thank you.

**Comment by mattaningram** [comment]
When animating an element with transforms or opacity it can create a new z-index stacking context, so I'm guessing something along those lines is what is causing your issue. Can you provide a code example or sandbox or some more information so we can help you figure it out?

**Comment by mattaningram** [comment]
Closing this for now, let me know if this issue still comes up for you.

**Comment by kato68** [comment]
Hi, I have same issue .please help to solve it

**Comment by mattaningram** [comment]
@kato68 Can you show a screenshot or code sandbox example of the issue you are running into?

**Comment by kato68** [comment]
@mattaningram  It interferes with Bootstrap modal
https://tjfjgn.csb.app/
