### ISSUE TITLE
Mirrored Stagger?

### ISSUE THREAD

**Issue by DoradoFlamingo** [ingram-projects/animxyz#65]
This would be more of an enhancement because I don't think this is possible and needed to make this. Is there a way to mirror staggers? What I mean is, if you have 5 list items then the xyz-index would be:

1  2  3  4  5

But I have an animation where I want them to transition mirrored from side to side so:

1  2  3  2  1

**Comment by mattaningram** [comment]
Interesting idea! I'd have to look into nth-child rules to make it happen automatically with an xyz utility, but if you are ok with a little more setup you can set the `--xyz-index` variable on each element to determine the order of animation in a stagger. You can either hardcode each element's `--xyz-index` or you can use some JS to automatically set the variable for a list of elements where you don't know the length.

You can see the docs for staggering here: https://animxyz.com/docs#stagger

Let me know if any of that makes sense or you have any issues using the index variable.

**Comment by DoradoFlamingo** [comment]
yeah thought about it, i'll give it a shot cheers! 👍🏼

**Comment by DoradoFlamingo** [comment]
just to let you know it works by setting the xyz-index as you suggested in the order mentioned in the original post.

**Comment by mattaningram** [comment]
@DoradoFlamingo That's great to hear! Please let us know of any other feedback or issues you have.
