### ISSUE TITLE
How to prevent initial appear animation?

### ISSUE THREAD

**Issue by 7iomka** [ingram-projects/animxyz#69]
Hi
I have in vue
```
<XyzTransition
        appear
        xyz="fade in-left-25% out-right-25%"
        mode="out-in"
        duration="auto"
      >
        <router-view role="main"></router-view>
      </XyzTransition>
```

When page opened first time (initial) I **don't** want to see animation (fase-translation from left to right), but when I go to some route, I want to see that animation.
How to do that?
Another question, when I go back (with browser back button), I wan't to see inverse animation, but now I see the same animation. 
Thanks!

**Comment by Sananes** [comment]
@7iomka does my post for this sound familiar to you https://github.com/ingram-projects/animxyz/issues/67 ?

**Comment by milesingrams** [comment]
I'm curious why you would see the left-to-right transition on load? If you take a look at our docs for Vue we have a template for vue-router that is almost identical to this and you see only the fade on initial load and the slide on route change only. I wonder why it might be functioning differently in your case

https://codesandbox.io/s/animxyz-vue-2-router-0l48w

In regards to reversing the animation on back button pressed, that will require some javascript. Essentially Vue is running the `xyz-in` animation (fade in-left-25%) for the new route, and the `xyz-out` (fade out-right-25%) animation for the old route components regardless if you are clicking a new route or pressing the back button. To reverse this based on a certain criteria you need to swap those. A good way to do that would be to use the `v-xyz` directive do dynamically change the utilities. Here is an example of tabs that reverses direction using `v-xyz` based on the previous and next tab index: 

https://animxyz.com/docs?tab=examples&example=Tabs#practical-examples
