### ISSUE TITLE
tree shake? purge css support

### ISSUE THREAD

**Issue by ricky11** [ingram-projects/animxyz#76]
nice utility, but ads 10kb to my js bundle (similar to tailwind, but i can purge that)

anyway  i can shake some off or purge the classes or js?

Thanks
R

**Comment by milesingrams** [comment]
I have been using the more recent versions of PurgeCSS with a vue 3 project and it's working perfectly. I do think the old versions of PurgeCSS did not handle attribute selectors well. Here is my PurgeCSS config. (This is almost identical to the vue-cli-plugin-purgecss with the only change being adding the `%` signs to the line: `return contentWithoutStyleBlocks.match(/[A-Za-z0-9-_/:%]*[A-Za-z0-9-_/%]+/g) || []`
This allows the `%` based utilities like `xyz="up-100%"`

```javascript
{
	content: ['src/**/*.vue', 'index.html'],
	defaultExtractor(content) {
		const contentWithoutStyleBlocks = content.replace(/<style[^]+?<\/style>/gi, '')
		return contentWithoutStyleBlocks.match(/[A-Za-z0-9-_/:%]*[A-Za-z0-9-_/%]+/g) || []
	},
	safelist: [
		/-(leave|enter|appear)(|-(to|from|active))$/,
		/^(?!(|.*?:)cursor-move).+-move$/,
		/^router-link(|-exact)-active$/,
		/data-v-.*/,
	],
}
```

**Comment by ricky11** [comment]
How much kb did you save after it? if you just used one or two styles?

Thanks for that, im using vue 2 which is with webpack 4.

i suppose i can still chain the purge config with vue2 and the latest purgecss

it would be awesome if you could share the config if you have it.

**Comment by milesingrams** [comment]
So sorry for the very late response. Not sure if this is still an issue but here is the full postcss config I use that worked:
```
const presetEnv = require('postcss-preset-env')
const purgecss = require('@fullhuman/postcss-purgecss')

module.exports = {
	plugins: [
		presetEnv(),
		process.env.NODE_ENV === 'production' &&
			purgecss({
				content: ['src/**/*.vue', 'index.html'],
				defaultExtractor(content) {
					const contentWithoutStyleBlocks = content.replace(/<style[^]+?<\/style>/gi, '')
					return contentWithoutStyleBlocks.match(/[A-Za-z0-9-_/:%]*[A-Za-z0-9-_/%]+/g) || []
				},
				safelist: [
					/-(leave|enter|appear)(|-(to|from|active))$/,
					/^(?!(|.*?:)cursor-move).+-move$/,
					/^router-link(|-exact)-active$/,
					/data-v-.*/,
					/^xyz-.+$/,
				],
			}),
	],
}
```

**Comment by ricky11** [comment]
this helps will try it out.
