### ISSUE TITLE
Preact support request

### ISSUE THREAD

**Issue by EthanStandel** [ingram-projects/animxyz#80]
When I use Preact with Animxyz using `preact/compat` the animations just constantly go in and out when an animated element is supposed to exist

**Comment by EthanStandel** [comment]
Feel free to close as `wontfix` if there's no way this is on your roadmap

**Comment by mattaningram** [comment]
Can you setup an example Codesandbox or something similar to demonstrate the issue? We can take a look.

**Comment by EthanStandel** [comment]
@mattaningram I have a Next app deployed with Vercel, so I can just show you the historic deployment and the code at that particular commit

[Code](https://github.com/EthanStandel/cakeelizabethdotcom/blob/67ca0d749721359e27d3235165aafba3b761c09d/src/components/ImageCarouselOverlay.tsx#L86)
[Deployment (click a photo thumbnail to see the issue)](https://cakeelizabethdotcom-6bn85pgj3-cakeelizabeth.vercel.app/weddings)
[Working deployment with the only difference being regular React](https://cakeelizabethstaging.vercel.app/weddings)

**Comment by milesingrams** [comment]
We use React Transition Group behind the scenes and I don't think that works with Preact. Last issue related to it is: https://github.com/preactjs/preact-compat/issues/14

Gonna close as `wontfix` but feel free to explore the answers to that thread and see if any sort of import proxy might work.

**Comment by EthanStandel** [comment]
@milesingrams that's alright, thanks for looking into it!
