### ISSUE TITLE
Change default perspective to none

### ISSUE THREAD

**Issue by xxSkyy** [ingram-projects/animxyz#87]
Since firefox (93) there are slight change that `perspective(0)` and `perspective(none)` are not equal but other browsers take them as the same. And in firefox animations are actually glitchy.

Here's all explained
https://bugzilla.mozilla.org/show_bug.cgi?id=1734999

**Comment by mattaningram** [comment]
Hmmm I just noticed that perspective is broken in Chrome as well. The banner on the home page is behaving with a very intense perspective despite it being set to `perspective: 1000px`. Firefox showing same behavior. I wonder if this is related.

**Comment by mattaningram** [comment]
So I have a deploy preview here with your suggested fix, and it works great in Chrome and Firefox, but it breaks perspective in Safari. https://deploy-preview-88--animxyz.netlify.app/

**Comment by mattaningram** [comment]
This is now fixed in `v0.6.6` and should work for both old and new versions of browsers. Thank you for catching this and suggesting fix @xxSkyy!

**Comment by xxSkyy** [comment]
Tried and now works good! Thank you for rapid fix on it!
