### ISSUE TITLE
Struggling to get it to work using React

### ISSUE THREAD

**Issue by cryptobench** [ingram-projects/animxyz#90]
Hello! 

First of I want to say that your project looks great!

I'm trying to get it work with react but i'm having trouble locally, so I created a CodeSandbox.

Here's what i've been doing, but nothing appears to be happening. I'm 100% doing something wrong, but I would greatly appreciate some help.

https://codesandbox.io/s/ecstatic-bash-26neo?file=/src/App.js

**Comment by cryptobench** [comment]
Importing the library via <head> causes it to work, but it won't without.

**Comment by mattaningram** [comment]
Hey @cryptobench thanks for checking out AnimXYZ! I think this is a simple fix, you just need to import the core AnimXYZ CSS file.

Add the line `import "@animxyz/core";` at the top of the `App.js` file and it works in your sandbox: https://codesandbox.io/s/amazing-dew-g70rx?file=/src/App.js
